// Code generated by MockGen. DO NOT EDIT.
// Source: ../logs.go

// Package logstest is a generated GoMock package.
package logstest

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRecordStore is a mock of RecordStore interface.
type MockRecordStore[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockRecordStoreMockRecorder[T]
}

// MockRecordStoreMockRecorder is the mock recorder for MockRecordStore.
type MockRecordStoreMockRecorder[T any] struct {
	mock *MockRecordStore[T]
}

// NewMockRecordStore creates a new mock instance.
func NewMockRecordStore[T any](ctrl *gomock.Controller) *MockRecordStore[T] {
	mock := &MockRecordStore[T]{ctrl: ctrl}
	mock.recorder = &MockRecordStoreMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordStore[T]) EXPECT() *MockRecordStoreMockRecorder[T] {
	return m.recorder
}

// ForEach mocks base method.
func (m *MockRecordStore[T]) ForEach(fn func(string, *T) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForEach", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForEach indicates an expected call of ForEach.
func (mr *MockRecordStoreMockRecorder[T]) ForEach(fn interface{}) *RecordStoreForEachCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForEach", reflect.TypeOf((*MockRecordStore[T])(nil).ForEach), fn)
	return &RecordStoreForEachCall[T]{Call: call}
}

// RecordStoreForEachCall wrap *gomock.Call
type RecordStoreForEachCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RecordStoreForEachCall[T]) Return(arg0 error) *RecordStoreForEachCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RecordStoreForEachCall[T]) Do(f func(func(string, *T) error) error) *RecordStoreForEachCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RecordStoreForEachCall[T]) DoAndReturn(f func(func(string, *T) error) error) *RecordStoreForEachCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockRecordStore[T]) Get(identifier string) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", identifier)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRecordStoreMockRecorder[T]) Get(identifier interface{}) *RecordStoreGetCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRecordStore[T])(nil).Get), identifier)
	return &RecordStoreGetCall[T]{Call: call}
}

// RecordStoreGetCall wrap *gomock.Call
type RecordStoreGetCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RecordStoreGetCall[T]) Return(arg0 *T, arg1 error) *RecordStoreGetCall[T] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RecordStoreGetCall[T]) Do(f func(string) (*T, error)) *RecordStoreGetCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RecordStoreGetCall[T]) DoAndReturn(f func(string) (*T, error)) *RecordStoreGetCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Set mocks base method.
func (m *MockRecordStore[T]) Set(identifier string, record *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", identifier, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRecordStoreMockRecorder[T]) Set(identifier, record interface{}) *RecordStoreSetCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRecordStore[T])(nil).Set), identifier, record)
	return &RecordStoreSetCall[T]{Call: call}
}

// RecordStoreSetCall wrap *gomock.Call
type RecordStoreSetCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *RecordStoreSetCall[T]) Return(arg0 error) *RecordStoreSetCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *RecordStoreSetCall[T]) Do(f func(string, *T) error) *RecordStoreSetCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *RecordStoreSetCall[T]) DoAndReturn(f func(string, *T) error) *RecordStoreSetCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
