// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: internal/proto/logs/v1/logs.proto

package logsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerEvent int32

const (
	ServerEvent_SERVER_EVENT_UNSPECIFIED ServerEvent = 0
	ServerEvent_SERVER_EVENT_LAUNCHED    ServerEvent = 1
	ServerEvent_SERVER_EVENT_STOPPED     ServerEvent = 2
)

// Enum value maps for ServerEvent.
var (
	ServerEvent_name = map[int32]string{
		0: "SERVER_EVENT_UNSPECIFIED",
		1: "SERVER_EVENT_LAUNCHED",
		2: "SERVER_EVENT_STOPPED",
	}
	ServerEvent_value = map[string]int32{
		"SERVER_EVENT_UNSPECIFIED": 0,
		"SERVER_EVENT_LAUNCHED":    1,
		"SERVER_EVENT_STOPPED":     2,
	}
)

func (x ServerEvent) Enum() *ServerEvent {
	p := new(ServerEvent)
	*p = x
	return p
}

func (x ServerEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_logs_v1_logs_proto_enumTypes[0].Descriptor()
}

func (ServerEvent) Type() protoreflect.EnumType {
	return &file_internal_proto_logs_v1_logs_proto_enumTypes[0]
}

func (x ServerEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerEvent.Descriptor instead.
func (ServerEvent) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_logs_v1_logs_proto_rawDescGZIP(), []int{0}
}

type InitEvent int32

const (
	InitEvent_INIT_EVENT_UNSPECIFIED InitEvent = 0
	InitEvent_INIT_EVENT_STARTED     InitEvent = 1
	InitEvent_INIT_EVENT_COMPLETED   InitEvent = 2
	InitEvent_INIT_EVENT_FAILED      InitEvent = 3
)

// Enum value maps for InitEvent.
var (
	InitEvent_name = map[int32]string{
		0: "INIT_EVENT_UNSPECIFIED",
		1: "INIT_EVENT_STARTED",
		2: "INIT_EVENT_COMPLETED",
		3: "INIT_EVENT_FAILED",
	}
	InitEvent_value = map[string]int32{
		"INIT_EVENT_UNSPECIFIED": 0,
		"INIT_EVENT_STARTED":     1,
		"INIT_EVENT_COMPLETED":   2,
		"INIT_EVENT_FAILED":      3,
	}
)

func (x InitEvent) Enum() *InitEvent {
	p := new(InitEvent)
	*p = x
	return p
}

func (x InitEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InitEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_logs_v1_logs_proto_enumTypes[1].Descriptor()
}

func (InitEvent) Type() protoreflect.EnumType {
	return &file_internal_proto_logs_v1_logs_proto_enumTypes[1]
}

func (x InitEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InitEvent.Descriptor instead.
func (InitEvent) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_logs_v1_logs_proto_rawDescGZIP(), []int{1}
}

type AcquisitionEvent int32

const (
	AcquisitionEvent_ACQUISITION_EVENT_UNSPECIFIED AcquisitionEvent = 0
	AcquisitionEvent_ACQUISITION_EVENT_ACQUIRED    AcquisitionEvent = 1
	AcquisitionEvent_ACQUISITION_EVENT_RELEASED    AcquisitionEvent = 2
)

// Enum value maps for AcquisitionEvent.
var (
	AcquisitionEvent_name = map[int32]string{
		0: "ACQUISITION_EVENT_UNSPECIFIED",
		1: "ACQUISITION_EVENT_ACQUIRED",
		2: "ACQUISITION_EVENT_RELEASED",
	}
	AcquisitionEvent_value = map[string]int32{
		"ACQUISITION_EVENT_UNSPECIFIED": 0,
		"ACQUISITION_EVENT_ACQUIRED":    1,
		"ACQUISITION_EVENT_RELEASED":    2,
	}
)

func (x AcquisitionEvent) Enum() *AcquisitionEvent {
	p := new(AcquisitionEvent)
	*p = x
	return p
}

func (x AcquisitionEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AcquisitionEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_logs_v1_logs_proto_enumTypes[2].Descriptor()
}

func (AcquisitionEvent) Type() protoreflect.EnumType {
	return &file_internal_proto_logs_v1_logs_proto_enumTypes[2]
}

func (x AcquisitionEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AcquisitionEvent.Descriptor instead.
func (AcquisitionEvent) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_logs_v1_logs_proto_rawDescGZIP(), []int{2}
}

type Caller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line int64  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Hash string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Caller) Reset() {
	*x = Caller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Caller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Caller) ProtoMessage() {}

func (x *Caller) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Caller.ProtoReflect.Descriptor instead.
func (*Caller) Descriptor() ([]byte, []int) {
	return file_internal_proto_logs_v1_logs_proto_rawDescGZIP(), []int{0}
}

func (x *Caller) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Caller) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Caller) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ServerRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs []*ServerLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *ServerRecord) Reset() {
	*x = ServerRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRecord) ProtoMessage() {}

func (x *ServerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRecord.ProtoReflect.Descriptor instead.
func (*ServerRecord) Descriptor() ([]byte, []int) {
	return file_internal_proto_logs_v1_logs_proto_rawDescGZIP(), []int{1}
}

func (x *ServerRecord) GetLogs() []*ServerLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ServerLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event     ServerEvent `protobuf:"varint,1,opt,name=event,proto3,enum=internal.proto.logs.v1.ServerEvent" json:"event,omitempty"`
	Addr      string      `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Context   []*Caller   `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty"`
	Timestamp int64       `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ServerLog) Reset() {
	*x = ServerLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLog) ProtoMessage() {}

func (x *ServerLog) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLog.ProtoReflect.Descriptor instead.
func (*ServerLog) Descriptor() ([]byte, []int) {
	return file_internal_proto_logs_v1_logs_proto_rawDescGZIP(), []int{2}
}

func (x *ServerLog) GetEvent() ServerEvent {
	if x != nil {
		return x.Event
	}
	return ServerEvent_SERVER_EVENT_UNSPECIFIED
}

func (x *ServerLog) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServerLog) GetContext() []*Caller {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ServerLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type InitRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs []*InitLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *InitRecord) Reset() {
	*x = InitRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRecord) ProtoMessage() {}

func (x *InitRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRecord.ProtoReflect.Descriptor instead.
func (*InitRecord) Descriptor() ([]byte, []int) {
	return file_internal_proto_logs_v1_logs_proto_rawDescGZIP(), []int{3}
}

func (x *InitRecord) GetLogs() []*InitLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type InitLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event     InitEvent `protobuf:"varint,1,opt,name=event,proto3,enum=internal.proto.logs.v1.InitEvent" json:"event,omitempty"`
	Context   []*Caller `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	Timestamp int64     `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *InitLog) Reset() {
	*x = InitLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitLog) ProtoMessage() {}

func (x *InitLog) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitLog.ProtoReflect.Descriptor instead.
func (*InitLog) Descriptor() ([]byte, []int) {
	return file_internal_proto_logs_v1_logs_proto_rawDescGZIP(), []int{4}
}

func (x *InitLog) GetEvent() InitEvent {
	if x != nil {
		return x.Event
	}
	return InitEvent_INIT_EVENT_UNSPECIFIED
}

func (x *InitLog) GetContext() []*Caller {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *InitLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AcquisitionRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Max  int64             `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	Logs []*AcquisitionLog `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (x *AcquisitionRecord) Reset() {
	*x = AcquisitionRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquisitionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquisitionRecord) ProtoMessage() {}

func (x *AcquisitionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquisitionRecord.ProtoReflect.Descriptor instead.
func (*AcquisitionRecord) Descriptor() ([]byte, []int) {
	return file_internal_proto_logs_v1_logs_proto_rawDescGZIP(), []int{5}
}

func (x *AcquisitionRecord) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *AcquisitionRecord) GetLogs() []*AcquisitionLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type AcquisitionLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event     AcquisitionEvent `protobuf:"varint,1,opt,name=event,proto3,enum=internal.proto.logs.v1.AcquisitionEvent" json:"event,omitempty"`
	N         int64            `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	Context   []*Caller        `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty"`
	Timestamp int64            `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *AcquisitionLog) Reset() {
	*x = AcquisitionLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquisitionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquisitionLog) ProtoMessage() {}

func (x *AcquisitionLog) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logs_v1_logs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquisitionLog.ProtoReflect.Descriptor instead.
func (*AcquisitionLog) Descriptor() ([]byte, []int) {
	return file_internal_proto_logs_v1_logs_proto_rawDescGZIP(), []int{6}
}

func (x *AcquisitionLog) GetEvent() AcquisitionEvent {
	if x != nil {
		return x.Event
	}
	return AcquisitionEvent_ACQUISITION_EVENT_UNSPECIFIED
}

func (x *AcquisitionLog) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *AcquisitionLog) GetContext() []*Caller {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AcquisitionLog) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_proto_logs_v1_logs_proto protoreflect.FileDescriptor

var file_internal_proto_logs_v1_logs_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x44, 0x0a, 0x06, 0x43,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x22, 0x45, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x35, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0xb2, 0x01, 0x0a, 0x09, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x12, 0x39, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x38, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x41, 0x0a,
	0x0a, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x33, 0x0a, 0x04, 0x6c,
	0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73,
	0x22, 0x9a, 0x01, 0x0a, 0x07, 0x49, 0x6e, 0x69, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x37, 0x0a, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x61, 0x0a,
	0x11, 0x41, 0x63, 0x71, 0x75, 0x69, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x6d, 0x61, 0x78, 0x12, 0x3a, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x71, 0x75,
	0x69, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x73,
	0x22, 0xb6, 0x01, 0x0a, 0x0e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x6f, 0x67, 0x12, 0x3e, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x28, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x71, 0x75,
	0x69, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x6e, 0x12, 0x38, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c,
	0x65, 0x72, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x60, 0x0a, 0x0b, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x45, 0x52, 0x56,
	0x45, 0x52, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52,
	0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x4c, 0x41, 0x55, 0x4e, 0x43, 0x48, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x56, 0x45, 0x4e,
	0x54, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x70, 0x0a, 0x09, 0x49,
	0x6e, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x16, 0x49, 0x4e, 0x49, 0x54,
	0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x49, 0x54, 0x5f, 0x45, 0x56, 0x45,
	0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14,
	0x49, 0x4e, 0x49, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c,
	0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x4e, 0x49, 0x54, 0x5f, 0x45,
	0x56, 0x45, 0x4e, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x2a, 0x75, 0x0a,
	0x10, 0x41, 0x63, 0x71, 0x75, 0x69, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x21, 0x0a, 0x1d, 0x41, 0x43, 0x51, 0x55, 0x49, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x43, 0x51, 0x55, 0x49, 0x53, 0x49, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x43, 0x51, 0x55, 0x49, 0x52,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x41, 0x43, 0x51, 0x55, 0x49, 0x53, 0x49, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x4c, 0x45, 0x41, 0x53,
	0x45, 0x44, 0x10, 0x02, 0x42, 0xe2, 0x01, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x73,
	0x2e, 0x76, 0x31, 0x42, 0x09, 0x4c, 0x6f, 0x67, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x69,
	0x63, 0x68, 0x69, 0x74, 0x61, 0x6b, 0x61, 0x68, 0x61, 0x73, 0x68, 0x69, 0x2f, 0x72, 0x73, 0x6d,
	0x61, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x6c, 0x6f, 0x67, 0x73, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x49, 0x50, 0x4c, 0xaa, 0x02, 0x16, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x73, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x16, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5c, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x5c, 0x4c, 0x6f, 0x67, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x22, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x5c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x4c, 0x6f, 0x67, 0x73, 0x5c, 0x56,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x19,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x3a, 0x3a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x3a,
	0x3a, 0x4c, 0x6f, 0x67, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_proto_logs_v1_logs_proto_rawDescOnce sync.Once
	file_internal_proto_logs_v1_logs_proto_rawDescData = file_internal_proto_logs_v1_logs_proto_rawDesc
)

func file_internal_proto_logs_v1_logs_proto_rawDescGZIP() []byte {
	file_internal_proto_logs_v1_logs_proto_rawDescOnce.Do(func() {
		file_internal_proto_logs_v1_logs_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_logs_v1_logs_proto_rawDescData)
	})
	return file_internal_proto_logs_v1_logs_proto_rawDescData
}

var file_internal_proto_logs_v1_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_proto_logs_v1_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_proto_logs_v1_logs_proto_goTypes = []interface{}{
	(ServerEvent)(0),          // 0: internal.proto.logs.v1.ServerEvent
	(InitEvent)(0),            // 1: internal.proto.logs.v1.InitEvent
	(AcquisitionEvent)(0),     // 2: internal.proto.logs.v1.AcquisitionEvent
	(*Caller)(nil),            // 3: internal.proto.logs.v1.Caller
	(*ServerRecord)(nil),      // 4: internal.proto.logs.v1.ServerRecord
	(*ServerLog)(nil),         // 5: internal.proto.logs.v1.ServerLog
	(*InitRecord)(nil),        // 6: internal.proto.logs.v1.InitRecord
	(*InitLog)(nil),           // 7: internal.proto.logs.v1.InitLog
	(*AcquisitionRecord)(nil), // 8: internal.proto.logs.v1.AcquisitionRecord
	(*AcquisitionLog)(nil),    // 9: internal.proto.logs.v1.AcquisitionLog
}
var file_internal_proto_logs_v1_logs_proto_depIdxs = []int32{
	5, // 0: internal.proto.logs.v1.ServerRecord.logs:type_name -> internal.proto.logs.v1.ServerLog
	0, // 1: internal.proto.logs.v1.ServerLog.event:type_name -> internal.proto.logs.v1.ServerEvent
	3, // 2: internal.proto.logs.v1.ServerLog.context:type_name -> internal.proto.logs.v1.Caller
	7, // 3: internal.proto.logs.v1.InitRecord.logs:type_name -> internal.proto.logs.v1.InitLog
	1, // 4: internal.proto.logs.v1.InitLog.event:type_name -> internal.proto.logs.v1.InitEvent
	3, // 5: internal.proto.logs.v1.InitLog.context:type_name -> internal.proto.logs.v1.Caller
	9, // 6: internal.proto.logs.v1.AcquisitionRecord.logs:type_name -> internal.proto.logs.v1.AcquisitionLog
	2, // 7: internal.proto.logs.v1.AcquisitionLog.event:type_name -> internal.proto.logs.v1.AcquisitionEvent
	3, // 8: internal.proto.logs.v1.AcquisitionLog.context:type_name -> internal.proto.logs.v1.Caller
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_internal_proto_logs_v1_logs_proto_init() }
func file_internal_proto_logs_v1_logs_proto_init() {
	if File_internal_proto_logs_v1_logs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_logs_v1_logs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Caller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_logs_v1_logs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_logs_v1_logs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_logs_v1_logs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_logs_v1_logs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_logs_v1_logs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquisitionRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_logs_v1_logs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquisitionLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_logs_v1_logs_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_logs_v1_logs_proto_goTypes,
		DependencyIndexes: file_internal_proto_logs_v1_logs_proto_depIdxs,
		EnumInfos:         file_internal_proto_logs_v1_logs_proto_enumTypes,
		MessageInfos:      file_internal_proto_logs_v1_logs_proto_msgTypes,
	}.Build()
	File_internal_proto_logs_v1_logs_proto = out.File
	file_internal_proto_logs_v1_logs_proto_rawDesc = nil
	file_internal_proto_logs_v1_logs_proto_goTypes = nil
	file_internal_proto_logs_v1_logs_proto_depIdxs = nil
}
